# Generated by Django 4.2.26 on 2026-05-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_points",
                        to="devices.device",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_points",
                        to="devices.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["ts"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "ts"], name="telemetry_r_sensor__d762bc_idx"
                    ),
                    models.Index(
                        fields=["device", "ts"], name="telemetry_r_device__1e360c_idx"
                    ),
                ],
            },
        ),
    ]
