# Generated by Django 4.2.26 on 2026-05-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudDeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(default="Huawei Cloud IoTDA", max_length=64),
                ),
                ("product_id", models.CharField(max_length=128)),
                ("cloud_device_id", models.CharField(max_length=128)),
                ("node_id", models.CharField(max_length=128)),
                (
                    "mqtt_status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("shadow_version", models.PositiveIntegerField(default=1)),
                (
                    "rule_engine",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("delayed", "Delayed"),
                            ("disconnected", "Disconnected"),
                            ("unbound", "Unbound"),
                        ],
                        default="unbound",
                        max_length=16,
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud",
                        to="devices.device",
                    ),
                ),
            ],
        ),
    ]
