# Generated by Django 4.2.26 on 2026-05-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_no", models.PositiveIntegerField(unique=True)),
                ("sn", models.CharField(max_length=64, unique=True)),
                ("lab_id", models.CharField(default="lab-embedded-01", max_length=64)),
                ("model", models.CharField(default="BearPi-HM Nano", max_length=64)),
                (
                    "firmware_version",
                    models.CharField(default="unknown", max_length=32),
                ),
                ("location", models.CharField(max_length=128)),
                ("owner", models.CharField(max_length=128)),
                ("member", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("warning", "Warning"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="offline",
                        max_length=16,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("register_time", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("cloud_twin_id", models.CharField(blank=True, max_length=128)),
                ("sample_rate", models.PositiveIntegerField(default=1)),
                ("abnormal_reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["slot_no"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("reboot", "Reboot"),
                            ("upgrade", "Upgrade"),
                            ("set_param", "Set Param"),
                        ],
                        max_length=32,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("acked", "Acked"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ack_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("unit", models.CharField(blank=True, max_length=16)),
                ("description", models.TextField(blank=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("latest_ts", models.DateTimeField(blank=True, null=True)),
                ("latest_value", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device_id", "id"],
                "unique_together": {("device", "code")},
            },
        ),
    ]
